### ISSUE TITLE
1.8.4.pre Release failure

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-cli#314]
- `bipm` - failure fixed after restart
- `nist` - failure related to dependency resolution issue, I assume that a new version of `metanorma-nist` has to be released
   ```
   Because relaton-cli >= 1.16.0 depends on relaton ~> 1.16.0
     and every version of glossarist depends on relaton ~> 1.15.0,
     relaton-cli >= 1.16.0 is incompatible with glossarist >= 0.
   And because every version of metanorma-plugin-glossarist depends on glossarist
   >= 0,
     relaton-cli >= 1.16.0 is incompatible with metanorma-plugin-glossarist >= 0.
   And because metanorma-standoc >= 2.4.4 depends on metanorma-plugin-glossarist ~>
   0.1.1
     and metanorma-standoc >= 2.6.0 depends on relaton-cli ~> 1.16.0,
     metanorma-standoc >= 2.6.0 cannot be used.
   So, because every version of metanorma-cli depends on metanorma-standoc ~> 2.6.0
     and Gemfile depends on metanorma-cli >= 0,
     version solving has failed.
   ```
- `ribose` and `bsi` has the same issue as `nist` but they don't block the release

**Comment by CAMOBAP** [comment]
@opoudjis could you please help fix/create a appropriate ticket for `metanorma-nist`

Once fixed, I will restart nist related jobs

**Comment by ronaldtse** [comment]
@CAMOBAP created tickets here:
* https://github.com/metanorma/metanorma-nist/issues/383
* https://github.com/metanorma/metanorma-bsi/issues/440
* https://github.com/metanorma/metanorma-ribose/issues/234

**Comment by ronaldtse** [comment]
@CAMOBAP I'd like to clarify -- none of Ribose, BSI or NIST are needed in the public metanorma-cli. Why is the release a failure?

**Comment by opoudjis** [comment]
No. NIST, BSI, and Ribose have all been released, as you can see if you fetch cli from github and bundle update:

````
Fetching https://github.com/metanorma/metanorma-cli
Fetching gem metadata from https://rubygems.pkg.github.com/metanorma/..
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
Using relaton-bib 1.16.0 (was 1.14.14)
Using pubid-iso 0.6.0 (was 0.5.3)
Using relaton-iso-bib 1.16.0 (was 1.14.0)
Using relaton-calconnect 1.16.0 (was 1.14.2)
Using relaton-ieee 1.16.0 (was 1.14.8)
Using relaton-ietf 1.16.0 (was 1.14.5)
Using relaton-iho 1.16.0 (was 1.14.3)
Using relaton-omg 1.16.0 (was 1.14.0)
Using relaton-3gpp 1.16.0 (was 1.14.6)
Using relaton-iana 1.16.0 (was 1.14.3)
Using relaton-nist 1.16.1 (was 1.14.9)
Using relaton-gb 1.16.0 (was 1.14.0)
Using relaton-iec 1.16.0 (was 1.14.4)
Using relaton-iso 1.16.0 (was 1.15.4)
Using relaton-ogc 1.16.0 (was 1.14.3)
Using relaton-un 1.16.0 (was 1.14.1)
Using relaton-bsi 1.16.0 (was 1.14.6)
Using relaton-cie 1.16.0 (was 1.14.1)
Using relaton-cen 1.16.3 (was 1.14.1)
Using relaton-bipm 1.16.0 (was 1.14.11)
Using relaton-jis 1.16.0 (was 1.14.4)
Using relaton-ccsds 1.16.0 (was 1.14.0)
Using relaton-oasis 1.16.0 (was 1.14.4)
Using relaton-itu 1.16.0 (was 1.14.3)
Using relaton-xsf 1.16.0 (was 1.14.0)
Using relaton-doi 1.16.0 (was 1.14.4)
Using relaton-ecma 1.16.0 (was 1.14.6)
Using relaton-w3c 1.16.0 (was 1.14.3)
Using relaton 1.16.0 (was 1.15.6)
Using glossarist 1.1.0 (was 1.0.9)
Using relaton-cli 1.16.0 (was 1.15.6)
Using metanorma-standoc 2.6.0 (was 2.5.5)
Using metanorma-generic 2.5.2 (was 2.5.1)
Using metanorma-itu 2.3.2 (was 2.3.1)
Using metanorma-ogc 2.4.2 (was 2.4.1)
Using metanorma-ietf 3.2.2 (was 3.2.1)
Using metanorma-ieee 1.1.2 (was 1.1.1)
Using metanorma-cc 2.3.2 (was 2.3.1)
Using metanorma-csa 2.3.2 (was 2.3.1)
Using metanorma-iho 0.8.2 (was 0.8.1)
Using metanorma-nist 2.3.3 (was 2.3.2)
Using metanorma-un 0.11.2 (was 0.11.1)
Using metanorma-iso 2.5.2 (was 2.5.1)
Using metanorma-iec 2.3.2 (was 2.3.1)
Using metanorma-bipm 2.3.2 (was 2.3.1)
Using metanorma-cli 1.8.4.pre (was 1.8.3) from https://github.com/metanorma/metanorma-cli (at main@2c9f290)
Bundle updated!
````

Glossarist was released just before I released 1.8.4.pre, and the gems involved are private, or fetched ad hoc; that might be the connection.

**Comment by CAMOBAP** [comment]
@opoudjis thanks for the confirmation, on GitHub actions we do something similar but in a few steps:

```
bundle remove metanorma-cli || true
bundle add metanorma-cli --path ..
bundle add sassc
```

And looks like it failed on the second step

We apply the bundle commands above to the https://github.com/metanorma/mn-samples-nist/blob/main/Gemfile

@opoudjis @ronaldtse maybe you have any idea why this happens?

I am sure that if I will replace those commands with simple `sed -i 's/^gem "metanorma-cli"$/'"'metanorma-cli\", path: \"..\"'"'/' Gemfile` it will work, but in my opinion it's wrong way to edit `Gemfile`s

**Comment by CAMOBAP** [comment]
Upd. I assume this affected the order, moving to sed or other in file replacement mechanism

**Comment by CAMOBAP** [comment]
Fixed, waiting for CI https://github.com/metanorma/metanorma-cli/actions/runs/6156596992 once passed we are ready for release

**Comment by CAMOBAP** [comment]
Issue still reproduces on CI while I checked the fix is works on local environment, investigation in progress

**Comment by ronaldtse** [comment]
Why don’t we use the “bundle add” command for the private gems too? 

The “sed” solution is likely not ideal…

**Comment by CAMOBAP** [comment]
> Why don’t we use the “bundle add” command for the private gems too?
> 
> The “sed” solution is likely not ideal…

We use it in flavor repositories, but for `metanorma-cli` we have to update only `metanorma-cli`. If we will decide to reinstall `metanorma-$flavor` the logic can become more complicated because we will have to handle `private` gems, `git` gems

Current approach `build add ... --skip-install`

**Comment by CAMOBAP** [comment]
I think we are ready for release the last master is "green" except `bsi` it looks like misconfiguration in Gemfile, probably we should move to `source: "https://rubygems.pkg.github.com/metanorma"` from `git: "https://github.com/metanorma/metanorma-bsi", branch: "main"` 

@ronaldtse @opoudjis let me know if we are ready I can initiate release (do a 1.8.4 tag on `metanorma-cli`)

**Comment by CAMOBAP** [comment]
`metanorma-cli` passed successfully, I will handle the rest

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP @opoudjis !

**Comment by CAMOBAP** [comment]
We still have an issue with BSI, yesterday I proposed "Gemfile cleanup" PR It's failed with this issue https://github.com/metanorma/mn-samples-bsi/actions/runs/6191758202/job/16810620665#step:5:9972

Based on it https://github.com/relaton/relaton-bib/issues/80 - was reported

Also we have issue with releases on metanorma-docker-private, it will be resolved in the scope of https://github.com/metanorma/metanorma-docker-private/issues/16

**Comment by CAMOBAP** [comment]
Closing this one
